import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "./Layout/LayoutWrapper";
import "antd/dist/reset.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Albert_Sans } from "next/font/google";
import { cookies } from "next/headers";

const albertSans = Albert_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-AlberSans",
});

export const metadata: Metadata = {
  title: "Level Up",
  description: "Generated by Level Up",
};

type RootLayoutProps = {
  children?: ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const access_token = cookies().get("access_token")?.value;

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/antd/4.16.13/antd.min.css"
        />
      </head>
      <body className={albertSans.className}>
        <AntdRegistry>
          <LayoutWrapper access_token={access_token}>{children}</LayoutWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
